spring.application.name=Peertube.Miner
server.port=8082
logging.level.com.Peertube.Miner.controller=DEBUG
PeerTubeMiner.baseuri=https://peertube.tv/api/v1

PeerTubeMiner.maxVideos = 10
PeerTubeMiner.maxComments = 10

videominer.uri=http://localhost:8080/videominer/channels

